tuning: Avoid ValueError on slow/loaded machines
On some particularly slow or heavily-loaded systems, the count of
bytes hashed in 100ms is very low.  In this case, tune_count() was
raising:

    ValueError: negative shift count

because of the way that the value is calculated.  This patch fixes
that case.

Signed-off-by: Daniel Kahn Gillmor <dkg@fifthhorseman.net>