removing all attempts to fiddle with pydist
These don't appear to be necessary anymore, and for whatever reason
the first line of python3-pgpy.dist ("-enum34 -3.4 python3-enum34") is
causing failures in dh_python3, despite being apparently valid
according to /usr/share/doc/dh-python/README.PyDist

The errors i see when this file is installed look like this:

    dh_python3 -O--buildsystem=pybuild
Traceback (most recent call last):
  File "/usr/bin/dh_python3", line 273, in <module>
    main()
  File "/usr/bin/dh_python3", line 201, in main
    dependencies.parse(stats, options)
  File "/usr/share/dh-python/dhpython/depends.py", line 239, in parse
    deps = parse_pydep(self.impl, fn, bdep=self.bdep, **section_options)
  File "/usr/share/dh-python/dhpython/pydist.py", line 265, in parse_pydep
    dependency = guess_deps(req=line)
  File "/usr/share/dh-python/dhpython/pydist.py", line 146, in guess_dependency
    data = load(impl)
  File "/usr/share/dh-python/dhpython/tools.py", line 234, in __call__
    self.cache[key] = self.func(*args, **kwargs)
  File "/usr/share/dh-python/dhpython/pydist.py", line 123, in load
    dist['versions'] = get_requested_versions(impl, dist['vrange'])
  File "/usr/share/dh-python/dhpython/version.py", line 406, in get_requested_versions
    minv = Version(major=0, minor=0) if vrange.minver is None else vrange.minver
  File "/usr/share/dh-python/dhpython/version.py", line 62, in __init__
    raise ValueError('major component is required')
ValueError: major component is required